main/attitude.h, main/bmp_altimeter.h
I used some methods defined in the bmp_altimeter.h class to return a reading of the altitude. Please let me know if this makes sense.
- Saad
=> added setGroundLevel()

main/apogee.h, main/gps.h, main/gy521_imu.h, main/main.ino, main/settings.h, sensor-testing/GY521_Electrosome/GY521_Electrosome.ino
This branch was incorrectly used ahead of `main`. From now on all changes will be concise  and compartmentalized so that PRs will be easy to review. Documentation will follow later today.
=> Moving changes to main branch

GETTING_STARTED.md, README.md
This comprehensive document should make contributions clear and easy for any beginner. No coding, Arduino, or GitHub experience required. 
Since I made this doc without going through all of the steps (such as downloading stuff), there will need to be another issue to walk through these steps with a volunteer beginner.
Also, there will need to be a testing section added regarding compilation and debugging.
=> Initial Contribution Guidelines

.gitignore, README.md
- Added vscode files to .gitignore so that they won't accidentally be tracked by git.
- corrected getting started link so it points to the correct page
=> Qol and fixes

.gitignore, platformio.ini
Added configuration file for PlatformIO. This allows building and deployment of code directly from VSCode. Yay! No more Arduino IDE!
=> Platform io config

GETTING_STARTED.md
Added documentation for PlatformIO installation
=> Platformio documentation

pull_request_template.md
People might not know what kind of info to provide in a PR description.
A template will force people to think about how to explain the work that they've done which will further reinforce what they learned in their mind. It'll also make code reviewing easier since the reviewer pretty much just needs to understand the description.
=> added simple PR template

main/main.ino
Added timing note for clarity #58
=> Added comment for clarity

main/data.h
Self explanatory
closes #78 
Processing teensy41 (platform: teensy; board: teensy41; framework: arduino)
-----------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensy41.html
PLATFORM: Teensy (4.17.0) > Teensy 4.1
HARDWARE: IMXRT1062 600MHz, 512KB RAM, 7.75MB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES:
- framework-arduinoteensy @ 1.157.220801 (1.57)     
- tool-teensy @ 1.157.0 (1.57)
- toolchain-gccarmnoneeabi @ 1.50401.190816 (5.4.1) 
Converting main.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 97 compatible libraries
Scanning dependencies...
Dependency Graph
|-- EWMA @ 1.0.2
|-- …
=> Changed time to us / previously ms

main/main.ino
This change causes the landing check to occur after data is transferred to the SD.
=> Prioritizes data transfer over landing check

main/main.ino
This probably isn't a bug, but it isn't currently necessary and it makes it harder to debug this function in its current configuration
Removed all use of `transitionDelay`
- compiled code with no errors or warnings
closes #86
=> Removed Transition Delay at Apogee

README.md
The software architecture can be a bit complicated to understand, a visualization would help
I made a flowchart on Miro for `main.ino`. It may be useful to make flowcharts for important functions in other files as well (such as attitude calculations)
- no testing necessary for a readme change
=> Added flowchart to readme

README.md
Some randos are still trying to contribute even though we have a note about limiting contributions to HLA members
Some randos are still trying to contribute even though we have a note about limiting contributions to HLA members
Made the statement into a heading so it'll pop out more. Also clarified that outsiders can contribute but can't use up the beginner issues.
- no testing needed since this change doesn't affect executable code
=> clarified external contribution rule

pull_request_template.md
There seems to be some confusion regarding filling out the PR template. The current template has a bullet already filled out in testing but it's not clear that the requestor actually did that testing.
A logging section was added so that it's clear that people actually compile their code before submitting it. Also, the testing example was commented out so that it's clear that it's an example. An additional `issues` section was added to link issues and auto close them.
From now on all PRs should have all sections of the template filled out in order to pass review. In cases where a section is not applicable, the requestor can state that in the section.
no testing was performed for this change since no executable code was changed.
=> Added detail to pull request template

main/gps.h
changed an arbitrary number for an actual variable which is in settings.h
closes #33 
- compiled code with no errors or warnings
=> GPS wait time integration

main/apogee.h, main/attitude.h, main/main.ino, main/ringQueue.h, main/settings.h, main/utils.h
There are some extraneous variables declared without clear purposes. There are also variables that use up more space than required. Finally, the variables need to have more precise declarations so we know how much size it uses.
Deleting extraneous variables and changing the variable declaration to lower sizes accordingly with their intended size. Also adjusting some variable to have more precise declarations. For example, changing `unsigned int` to `uint_32`
Compiled the code without any warnings or errors.
```
Processing teensy41 (platform: teensy; board: teensy41; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: …
```
=> Variable cleanup

main/main.ino
The buzzer is currently not working, so we'd like a fault tolerant way to know that the computer is on.
Added a `print` statement to transmit `beep` every time the buzzer would normally go off. This way we can see that the computer is on via our receiver.
- compiled code
- brick tested on Catalyst
=> Added virtual buzzer

main/data.h
The automated UI requires strict telemetry formatting, so this reformat will allow catalyst-2 to be compatible.
=> updated telemetry transmission to match with Catalyst-UI

main/bmp_altimeter.h, test/lib/mock_arduino.h, test/test_bmp_altimeter/test_main.cpp, test/test_utils/test_main.cpp
- added some unit tests for `bmpAltimeter.h`
- mocked `adafruitBMP`, `delay`, `micros()` somewhat lazily
- we may want to add more functionality to the mock sensor data in the future. We could either generate BS data or use data from an external input (i.e. flight data)
- mocked timing functions are currently useless, but we could probably integrate them with communication calls to get accurate timing estimates
- this would help with development of any kind of RTOS
- ran unit tests
=> Added unit tests for bmpAltimeter

main/bmp_altimeter.h, main/gy521_imu.h, platformio.ini, test/lib/mock_arduino.h, test/test_bmp_altimeter/test_main.cpp, test/test_gy521_imu/test_main.cpp, test/test_utils/test_main.cpp
- Added generic tests for gy521 (MPU6050)
- changed assertions to use the `DOUBLE` macro where necessary
- added mock Serial function (to be improved)
- ran unit tests
- this PR is built on top off and therefor gated by #138
=> Added unit tests for gy521 IMU

docs/GETTING_STARTED.md
Fix Catalyst-2 into Stimulant to avoid confusion because Repository renamed from Catalyst-2 to Stimulink.  Update new link for avionic lead contact.
Replace Catalyst-2 to Stimulink
Commit 1.  Replace Catalyst-2 to Stimulink
Commit 2.  Remove all whitespace automatic added by extension. Update new link for avionic lead contact.
=> fix Catalyst-2 to Stimulant

README.md
The instructions within the README section need to be changed in order to clarify when the pyros need to be attached, and the precautions needed to be implemented before them.
Edited the code and instructions to have clearer wording and included additional steps.
=> README Instructions change
